import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Clinical Radiance — full MD3 token system
        "surface": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "surface-variant": "#dae2fd",
        "surface-tint": "#00677d",
        "on-surface": "#131b2e",
        "on-surface-variant": "#3d494d",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "background": "#faf8ff",
        "on-background": "#131b2e",
        "outline": "#6d797e",
        "outline-variant": "#bcc9ce",
        "primary": "#00677d",
        "on-primary": "#ffffff",
        "primary-container": "#00b4d8",
        "on-primary-container": "#00414f",
        "primary-fixed": "#b3ebff",
        "primary-fixed-dim": "#4cd6fb",
        "on-primary-fixed": "#001f27",
        "on-primary-fixed-variant": "#004e5f",
        "inverse-primary": "#4cd6fb",
        "secondary": "#515f78",
        "on-secondary": "#ffffff",
        "secondary-container": "#d2e0fe",
        "on-secondary-container": "#55637d",
        "secondary-fixed": "#d6e3ff",
        "secondary-fixed-dim": "#b9c7e4",
        "on-secondary-fixed": "#0d1c32",
        "on-secondary-fixed-variant": "#39475f",
        "tertiary": "#006c49",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#19bc84",
        "on-tertiary-container": "#00442d",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "1rem",
        sm: "0.5rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "margin": "2rem",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["64px", { lineHeight: "72px", fontWeight: "800", letterSpacing: "-0.03em" }],
        "display-hero-mobile": ["38px", { lineHeight: "44px", fontWeight: "800" }],
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "30px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["15px", { lineHeight: "22px", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", fontWeight: "700" }],
      },
      boxShadow: {
        "glow-cyan": "0 8px 24px -4px rgba(0, 180, 216, 0.45)",
        "glow-cyan-sm": "0 4px 16px -4px rgba(0, 180, 216, 0.35)",
        "card": "0 10px 30px -10px rgba(15, 23, 42, 0.05)",
        "card-hover": "0 20px 40px -12px rgba(0, 180, 216, 0.2)",
        "nav": "0 2px 12px -2px rgba(19, 27, 46, 0.04)",
      },
      animation: {
        "ping-slow": "ping 2s cubic-bezier(0, 0, 0.2, 1) infinite",
        "fade-in": "fadeIn 0.3s ease-out",
        "slide-up": "slideUp 0.3s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
